services:
  company-profile:
    build:
      context: .
      dockerfile: Dockerfile
    image: company-profile:latest
    container_name: company-profile
    restart: always
    networks:
      - coolify
    expose:
      - "3000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - FORCE_HTTPS=true

networks:
  coolify:
    external: true
